#!/bin/bash
action=$1
if [ "$action" = "ps" -o "$action" = "images" -o "$action" = "stats" -o "$action" = "network" ]; then
        docker-ce $* | grep -Ev "node_static|static"
else
        docker-ce $*
fi
